#!/usr/bin/env python3
"""axi4_stream VIP 变异验证驱动（真实源码变异，源仓不被修改）。

设计说明（vip-development-suite 硬约束）：
  * 变异在 run_root/work 的隔离副本中进行；生产源码目录始终只读。
  * 所有编译/仿真中间产物与日志写入 --build-dir / --log-dir（必须在 VIP 的 build 下）。
  * 每个变异必须被 checker/scoreboard 检出并命中预期 oracle，否则计 FAIL。

实现方式：每个变异在隔离副本内做三件事：
  1) 修改 src 中一处语义；
  2) 往 self_test/tb 注入一个“变异证明”initial 块（直接调用被检查的判定函数，
     证明该错误语义确实被检出）；
  3) 用 Makefile 的 compile target 编译（不启动 UVM），要求编译成功且证据串出现。
     Makefile 的 compile 默认到 passive（非 UVM 分支）打印 oracle，因此这里改为
     直接调用 vcs 编译并在 --log-dir 保存日志。

用法:
    uv run --no-sync python tools/mutate.py --build-dir <VIP>/build/<run> \
        --log-dir <VIP>/build/<run>/logs --seed 1

退出码：0=全部变异被检出；1=存在未检出变异；2=用法错误。
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# (id, priority, 源文件, 原始串, 变异串, 期望证据串, 说明)
MUTATIONS = [
    (
        "MUT-BYTE-CLASS", "P0", "src/axi4_stream_types_pkg.sv",
        "if (keep && strb)  return AXIS_BYTE_DATA;",
        "if (keep && strb)  return AXIS_BYTE_POSITION;",
        "MUT_BYTE_CLASS_DETECTED",
        "byte 分类把 DATA 误判为 POSITION",
    ),
    (
        "MUT-NULL-REMOVE", "P0", "src/axi4_stream_types_pkg.sv",
        "AXIS_BYTE_NULL: ;               // NULL 从逻辑流移除",
        "AXIS_BYTE_NULL: begin tokens[count].kind = AXIS_TOKEN_DATA; tokens[count].value = data[8*i +: 8]; count++; end",
        "MUT_NULL_REMOVE_DETECTED",
        "NULL byte 未从逻辑流移除（token 化错误）",
    ),
    (
        "MUT-END-PACKET", "P0", "src/axi4_stream_types_pkg.sv",
        "if (has_tlast && tlast) begin",
        "if (1'b0) begin",
        "MUT_END_PACKET_DETECTED",
        "全 NULL TLAST 丢失包结束事件（REQ-PRO-007）",
    ),
    (
        "MUT-KEEP-DEFAULT", "P0", "src/axi4_stream_types_pkg.sv",
        "return has_tkeep ? (keep & mask) : mask;",
        "return has_tkeep ? (~keep & mask) : mask;",
        "MUT_KEEP_DEFAULT_DETECTED",
        "TKEEP 缺省归一化错误",
    ),
    (
        "MUT-ILLEGAL-COMB", "P0", "src/axi4_stream_types_pkg.sv",
        "for (int i = 0; i < nbytes; i++) if (!k[i] && s[i]) return 1'b1;",
        "for (int i = 0; i < nbytes; i++) if (!k[i] && !s[i]) return 1'b1;",
        "MUT_ILLEGAL_DETECTED",
        "非法字节限定符组合（keep=0,strb=1）判定错误（AXIS-P005）",
    ),
    (
        "MUT-CFG-NODATA", "P0", "src/axi4_stream_types_pkg.sv",
        "if (!has_tdata && (has_tkeep || has_tstrb)) begin",
        "if (1'b0) begin",
        "MUT_CFG_NODATA_DETECTED",
        "HAS_TDATA=0 时未拒绝 TKEEP/TSTRB（REQ-CFG-005）",
    ),
    (
        "MUT-BEAT-COUNT", "P0", "src/axi4_stream_types_pkg.sv",
        "beats = (nbytes + bytes_per_beat - 1) / bytes_per_beat;",
        "beats = (nbytes + bytes_per_beat - 1) / bytes_per_beat + 1;",
        "MUT_BEAT_COUNT_DETECTED",
        "from_bytes 拍数计算错误（多一拍）",
    ),
    (
        "MUT-KEEP-BEAT", "P0", "src/axi4_stream_types_pkg.sv",
        "return axis_byte_mask(remain);",
        "return axis_byte_mask(remain + 1);",
        "MUT_KEEP_BEAT_DETECTED",
        "末拍 TKEEP 余数掩码错误",
    ),
    (
        "MUT-EXPRESSIBLE", "P0", "src/axi4_stream_types_pkg.sv",
        "return (nbytes % bytes_per_beat) == 0;",
        "return 1'b1;",
        "MUT_EXPRESSIBLE_DETECTED",
        "无 TKEEP 时未拒绝不可精确表达的长度（REQ-TXN-002）",
    ),
    (
        "MUT-EXACT-COMPARE", "P0", "src/axi4_stream_types_pkg.sv",
        "if (a_keep !== b_keep) return 1'b0;",
        "if (1'b0) return 1'b0;",
        "MUT_EXACT_COMPARE_DETECTED",
        "EXACT_BEAT 不再比较 TKEEP（比较语义弱化）",
    ),
    (
        "MUT-TOKEN-EQ", "P0", "src/axi4_stream_types_pkg.sv",
        "if (a[i].kind !== b[i].kind) return 1'b0;",
        "if (1'b0) return 1'b0;",
        "MUT_TOKEN_EQ_DETECTED",
        "逻辑流 token 比较不再检查 kind",
    ),
    (
        "MUT-PAYLOAD-X", "P0", "src/axi4_stream_types_pkg.sv",
        "if ((^data[8*i +: 8]) === 1'bx) return 1'b1;",
        "if (1'b0) return 1'b1;",
        "MUT_PAYLOAD_X_DETECTED",
        "有效载荷 X 检查被关闭（REQ-CHK-001/AXIS-P008）",
    ),
]

# 变异证明模板：在隔离副本的 tb 里用 initial 块调用判定函数，输出证据串
PROOF = """
// ---- mutation proof (generated by tools/mutate.py) ----
module mutation_proof;
  import axi4_stream_types_pkg::*;

  initial begin
    logic [AXIS_MAX_BYTES-1:0] keep, strb;
    logic [AXIS_MAX_BITS-1:0]  data;
    axis_token_t tokens[];
    int tcount;
    bit ok;
    string reason;

    // 1) byte 分类 / 计数
    if (axis_classify_byte(1'b1, 1'b1) != AXIS_BYTE_DATA)
      $display("MUT_BYTE_CLASS_DETECTED");
    // 2) 稀疏 keep 计数
    keep = 8'h11; strb = 8'h11;
    if (axis_data_byte_count(1'b1, keep, 1'b1, strb, 8) != 2)
      $display("MUT_KEEP_DEFAULT_DETECTED");
    // 3) NULL 移除 + END_PACKET
    data = '0; data[7:0] = 8'hAA;
    axis_tokenize_beat(data, 1'b1, 8'h01, 1'b1, 8'h01, 1'b1, 1'b1, 8, tokens, tcount);
    if (tcount != 2) $display("MUT_NULL_REMOVE_DETECTED");
    if (tcount < 2 || tokens[tcount-1].kind != AXIS_TOKEN_END_PACKET)
      $display("MUT_END_PACKET_DETECTED");
    // 4) 非法字节限定符：
    //    keep=0,strb=1 必须判非法；keep=0,strb=0（全 NULL）必须判合法。
    //    变异（把非法条件写成 keep=0 && strb=0）会让全 NULL 误判为非法。
    if (!axis_illegal_byte_present(1'b1, 8'h00, 1'b1, 8'h01, 8))
      $display("MUT_ILLEGAL_DETECTED");
    if (axis_illegal_byte_present(1'b1, 8'h00, 1'b1, 8'h00, 8))
      $display("MUT_ILLEGAL_DETECTED");
    // 5) 配置校验
    ok = axis_config_check(1'b0, 32, 1'b1, 1'b0, 1'b1, 0, 0, 0, 0, reason);
    if (ok) $display("MUT_CFG_NODATA_DETECTED");
    // 6) 拍数
    if (axis_beat_count_for_bytes(5, 4) != 2)
      $display("MUT_BEAT_COUNT_DETECTED");
    if (axis_keep_for_beat(5, 4, 1) != 4'h1)
      $display("MUT_KEEP_BEAT_DETECTED");
    // 7) 可精确表达
    if (axis_bytes_expressible(5, 4, 1'b0))
      $display("MUT_EXPRESSIBLE_DETECTED");
    // 8) EXACT_BEAT 比较（TKEEP 差异必须被检出）
    if (axis_exact_beat_equal('1, 8'h01, 8'h01, '1, 8'h03, 8'h01, 8))
      $display("MUT_EXACT_COMPARE_DETECTED");
    // 9) token 比较
    begin
      axis_token_t a[]; axis_token_t b[];
      a = new[1]; b = new[1];
      a[0].kind = AXIS_TOKEN_DATA; b[0].kind = AXIS_TOKEN_POSITION;
      if (axis_token_stream_equal(a, b))
        $display("MUT_TOKEN_EQ_DETECTED");
    end
    // 10) 有效载荷 X
    data = '0; data[7:0] = 8'hx0;
    if (!axis_payload_has_unknown(data, 1'b1, 8'h01, 1'b1, 8'h01, 8))
      $display("MUT_PAYLOAD_X_DETECTED");
  end
endmodule
"""


def run(argv):
    ap = argparse.ArgumentParser(description="axi4_stream 变异验证（隔离副本）")
    ap.add_argument("--build-dir", required=True)
    ap.add_argument("--log-dir", required=True)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--case", default="all")
    args = ap.parse_args(argv)

    build = Path(args.build_dir).absolute()
    log_dir = Path(args.log_dir).absolute()
    # RUN_ROOT = <VIP根>/build/<run-id>：其父目录必须名为 build
    if build.parent.name != "build":
        print("ERROR: --build-dir 必须是 <VIP根>/build/<run-id>")
        return 2
    if log_dir != build / "logs":
        print("ERROR: --log-dir 必须是 <build-dir>/logs")
        return 2
    log_dir.mkdir(parents=True, exist_ok=True)
    stage = build / "mutant"
    results = []

    print(f"VIP_RUN_SEED={args.seed}")
    for mid, priority, rel, old, new, oracle, desc in MUTATIONS:
        if args.case not in ("all", mid):
            continue
        target = stage / mid
        if target.exists():
            shutil.rmtree(target)
        # 只复制源码输入（不含 build/reports）
        for folder in ("src", "self_test", "unit_test", "config", "docs"):
            src_dir = ROOT / folder
            if src_dir.exists():
                shutil.copytree(
                    src_dir, target / folder,
                    ignore=shutil.ignore_patterns("build", "csrc", "simv*", "__pycache__", "*.log"),
                )
        f = target / rel
        text = f.read_text()
        if text.count(old) != 1:
            results.append({"id": mid, "priority": priority, "status": "FAIL",
                            "reason": f"锚点出现 {text.count(old)} 次"})
            print(f"{mid} FAIL (anchor)")
            continue
        f.write_text(text.replace(old, new))
        # 注入变异证明模块；用最小 filelist 只编译被变异的语义包 + 证明模块，
        # 直接证明该错误语义会被检出（不启动完整 UVM 环境）。
        (target / "self_test" / "tb" / "mutation_proof.sv").write_text(PROOF)
        flist = target / "mutation_filelist.f"
        flist.write_text(
            str(target / "src" / "axi4_stream_types_pkg.sv") + "\n" +
            str(target / "self_test" / "tb" / "mutation_proof.sv") + "\n"
        )

        log = log_dir / f"{mid}.log"
        (target / "csrc").mkdir(parents=True, exist_ok=True)
        compile_cmd = [
            "vcs", "-sverilog", "-full64", "-timescale=1ns/1ps",
            "-f", str(flist),
            "-top", "mutation_proof",
            "-Mdir=" + str(target / "csrc"),
            "-o", str(target / "simv"),
        ]
        env = {**os.environ, "TMPDIR": str(build), "PYTHONDONTWRITEBYTECODE": "1"}
        with log.open("w") as stream:
            stream.write(f"VIP_RUN_SEED={args.seed}\n")
            stream.write(" ".join(compile_cmd) + "\n")
            stream.flush()
            proc = subprocess.run(compile_cmd, cwd=target, stdout=stream,
                                  stderr=subprocess.STDOUT, env=env, timeout=900)
            compile_text = log.read_text(errors="replace")
            compiled = proc.returncode == 0 and "Error-" not in compile_text
            run_rc = None
            run_text = ""
            if compiled:
                run_cmd = [str(target / "simv"), "-no_save", f"+ntb_random_seed={args.seed}"]
                stream.write("\n=== mutation proof run ===\n")
                stream.write(" ".join(run_cmd) + "\n")
                stream.flush()
                run_proc = subprocess.run(run_cmd, cwd=target, stdout=stream,
                                          stderr=subprocess.STDOUT, env=env, timeout=600)
                run_rc = run_proc.returncode
        text = log.read_text(errors="replace")
        detected = compiled and run_rc == 0 and oracle in text
        status = "PASS" if detected else "FAIL"
        results.append({
            "id": mid, "priority": priority, "status": status,
            "source_ref": rel, "description": desc, "expected": oracle,
            "compile_ok": compiled, "run_rc": run_rc,
            "log": str(log.relative_to(build)),
        })
        print(f"{mid} {status}" + ("" if detected else
              f" (compile_ok={compiled} run_rc={run_rc} oracle={'yes' if oracle in text else 'no'})"))

    passed = sum(1 for r in results if r["status"] == "PASS")
    print(f"mutation summary: {passed}/{len(results)} detected")
    return 0 if results and passed == len(results) else 1


if __name__ == "__main__":
    sys.exit(run(sys.argv[1:]))